# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "commander-6.2.1" = {
      name = "commander";
      packageName = "commander";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-6.2.1.tgz";
        sha512 = "U7VdrJFnJgo4xjrHpTzu0yrHPGImdsmD95ZlgYSEajAn2JKzDhDTPG9kBTefmObL2w/ngeZnilk+OV9CG3d7UA==";
      };
    };
    "debug-4.3.2" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.2.tgz";
        sha512 = "mOp8wKcvj7XxC78zLgw/ZA+6TSgkoE2C/ienthhRD298T7UNwAg9diBpLRxC0mOezLl4B0xV7M0cCO6P/O0Xhw==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "isomorphic-ws-4.0.1" = {
      name = "isomorphic-ws";
      packageName = "isomorphic-ws";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-ws/-/isomorphic-ws-4.0.1.tgz";
        sha512 = "BhBvN2MBpWTaSHdWRb/bwdZJ1WaehQ2L1KngkCkfLUGF0mAWAT1sQUQacEmQ0jXkFw/czDXPNQSL5u2/Krsz1w==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "obs-websocket-js-4.0.2" = {
      name = "obs-websocket-js";
      packageName = "obs-websocket-js";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/obs-websocket-js/-/obs-websocket-js-4.0.2.tgz";
        sha512 = "e+tGp0DQNXSnitc5lfuzEC1dG3VdWy7VLePUVb6aq7bC33Sgjoi695k0eOg4UPTIQI71Z9aJ+yn3nvBX9dQkEg==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "ws-7.4.4" = {
      name = "ws";
      packageName = "ws";
      version = "7.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.4.4.tgz";
        sha512 = "Qm8k8ojNQIMx7S+Zp8u/uHOx7Qazv3Yv4q68MiWWWOJhiwG5W3x7iqmRtJo8xxrciZUY4vRxUTJCKuRnF28ZZw==";
      };
    };
  };
in
{
  obs-cli = nodeEnv.buildNodePackage {
    name = "obs-cli";
    packageName = "obs-cli";
    version = "2.2.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/obs-cli/-/obs-cli-2.2.3.tgz";
      sha512 = "VFlFU/ZgKrQZuDb+2QFAIaPGD7fvQWsyOU3ADMlknOcVXvw2DY0ekMrMgtpLIo0OERxl89kHBFGvRbvfASzRfg==";
    };
    dependencies = [
      sources."commander-6.2.1"
      sources."debug-4.3.2"
      sources."inherits-2.0.4"
      sources."isomorphic-ws-4.0.1"
      sources."ms-2.1.2"
      sources."obs-websocket-js-4.0.2"
      sources."safe-buffer-5.2.1"
      sources."sha.js-2.4.11"
      sources."ws-7.4.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Remote control OBS from the command line.";
      homepage = "https://github.com/leafac/obs-cli#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
